const {contextBridge,ipcRenderer}=require('electron');
contextBridge.exposeInMainWorld('buddy',Object.freeze({
 bootstrap:()=>ipcRenderer.invoke('bootstrap'),
 windowInfo:()=>ipcRenderer.invoke('window-info'),
 presentation:change=>ipcRenderer.invoke('presentation',change),
 onPresentation:handler=>{const listener=(_,value)=>handler(value);ipcRenderer.on('presentation-update',listener);return()=>ipcRenderer.removeListener('presentation-update',listener);},
 saveState:(state,base)=>ipcRenderer.invoke('save-state',state,base),
 client:force=>ipcRenderer.invoke('client-status',force===true),
 ready:()=>ipcRenderer.invoke('main-ready'),
 onClient:handler=>{const listener=(_,value)=>handler(value);ipcRenderer.on('client-update',listener);return()=>ipcRenderer.removeListener('client-update',listener);},
 authorizeClient:()=>ipcRenderer.invoke('authorize-client'),
 updateData:()=>ipcRenderer.invoke('update-data'),
 catalogSource:url=>ipcRenderer.invoke('catalog-source',url),
 catalogCheck:()=>ipcRenderer.invoke('catalog-check'),
 catalogPreview:raw=>ipcRenderer.invoke('catalog-preview',raw),
 catalogApply:token=>ipcRenderer.invoke('catalog-apply',token),
 catalogRollback:()=>ipcRenderer.invoke('catalog-rollback'),
 catalogPersonal:entry=>ipcRenderer.invoke('catalog-personal',entry),
 catalogExport:()=>ipcRenderer.invoke('catalog-export'),
 refreshBuild:(id,role,source)=>ipcRenderer.invoke('refresh-build',id,role,source),
 refreshOpponentBuild:(id,role,opponent,source)=>ipcRenderer.invoke('refresh-opponent-build',id,role,opponent,source),
 refreshPairs:(members,source)=>ipcRenderer.invoke('refresh-pairs',members,source),
 applyRunes:(page,context)=>ipcRenderer.invoke('apply-runes',page,context),
 importItemSet:itemSet=>ipcRenderer.invoke('import-item-set',itemSet),
 exportItemSet:itemSet=>ipcRenderer.invoke('export-item-set',itemSet),
 copy:text=>ipcRenderer.invoke('copy',text),
 chooseDirectory:()=>ipcRenderer.invoke('choose-directory'),
 openLink:url=>ipcRenderer.invoke('open-link',url),
 exportState:()=>ipcRenderer.invoke('export-state'),
 importState:()=>ipcRenderer.invoke('import-state'),
 togglePin:()=>ipcRenderer.invoke('toggle-pin'),
 companionMode:value=>ipcRenderer.invoke('companion-mode',value),
 recoverGuide:()=>ipcRenderer.invoke('recover-guide'),
 onWindowLayout:handler=>{const listener=(_,value)=>handler(value);ipcRenderer.on('window-layout',listener);return()=>ipcRenderer.removeListener('window-layout',listener);},
 openGuide:selection=>ipcRenderer.invoke('open-guide',selection),
 updateGuide:selection=>ipcRenderer.invoke('update-guide',selection),
 matchupFocus:context=>ipcRenderer.invoke('matchup-focus',context),
 onGuideSelection:handler=>{const listener=(_,selection,meta)=>handler(selection,meta);ipcRenderer.on('guide-selection',listener);return()=>ipcRenderer.removeListener('guide-selection',listener);},
 onOpenBuild:handler=>{const listener=(_,selection,meta)=>handler(selection,meta);ipcRenderer.on('open-build',listener);return()=>ipcRenderer.removeListener('open-build',listener);},
 onProgress:handler=>{const listener=(_,msg)=>handler(msg);ipcRenderer.on('data-progress',listener);return()=>ipcRenderer.removeListener('data-progress',listener);},
 roomStatus:()=>ipcRenderer.invoke('room-status'),
 roomHost:nick=>ipcRenderer.invoke('room-host',nick),
 roomJoin:(target,nick)=>ipcRenderer.invoke('room-join',target,nick),
 roomRelay:(target,nick)=>ipcRenderer.invoke('room-relay',target,nick),
 roomLeave:()=>ipcRenderer.invoke('room-leave'),
 roomPublish:share=>ipcRenderer.invoke('room-publish',share),
 roomScan:()=>ipcRenderer.invoke('room-scan'),
 roomAddresses:()=>ipcRenderer.invoke('room-addresses'),
 onRoomUpdate:handler=>{const listener=(_,value)=>handler(value);ipcRenderer.on('room-update',listener);return()=>ipcRenderer.removeListener('room-update',listener);},
}));
